config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :drinks

end

app/models/drink.rb
class Drink < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  def index
    @drink = Drink.new
    @drinks = Drink.all
  end

  def create
    @drink = Drink.create(drink_params)
    if @drink.save
      redirect_to drinks_path
    else
      render :index
    end
  end

  def show
    @drink = Drink.find(params[:id])
  end

  def edit
    @drink = Drink.find(params[:id])
  end

  def update
    @drink = Drink.find(params[:id])
    @drink.update_attributes!(drink_params)

    redirect_to drink_path(@drink)
  end

  def destroy
    @drink = Drink.find(params[:id]).delete

    redirect_to drinks_path
  end

  private
  def drink_params
    params.require(:drink).permit(:brand, :flavor)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drinks/edit.html.erb
<%= form_for @drink do |f| %>
<p>
  <%= f.label :brand %>
  <%= f.text_field :brand %>
</p>
  <p>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </p>
  <p>
    <%= f.submit 'Update drink' %>
  </p>
<% end %>

app/views/drinks/index.html.erb
<%= form_for @drink do |f| %>
<p>
  <%= f.label :brand %>
  <%= f.text_field :brand %>
</p>
  <p>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </p>
  <p>
    <%= f.submit 'Add drink' %>
  </p>
<% end %>

<% @drinks.each do |drink| %>
<ul>
  <li>
    <%= drink.brand %>, <%= drink.flavor %>
  </li>
</ul>
<% end %>

app/views/drinks/show.html.erb
<ul>
  <li>
    <%= @drink.brand %>, <%= @drink.flavor %>
  </li>
</ul>

<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Delete drink', drink_path(@drink), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudDrinks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Add a drink', drinks_path %>